baseurl         = "https://confident-davinci-35e1f8.netlify.app/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "SNU Linguistics Department Colloquium"
  subtitle    = "Colloquia held at SNU Linguistics"

  cover       = "uploads/cover-lecture-room-modern.jpg"
  description = "This is a page where information regarding colloquia held at SNU Ling. Dep. in Fall 2020, funded by the 10 x 10 project."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = ""

  logo = "uploads/snuling_logo.png"
  orgName = "EM"
  orgWebsite = ""
  orgDescription = "Here is a description placeholder for your org"

  author = "Admin"
  authorAvatar = "uploads/userimage-linguistics.png"
  authorLocation = "Seoul, Republic of Korea"
  authorWebsite = ""
  authorDescription = "SNU Linguistics"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Colloquium"
  url = "/categories/colloquium/"
  weight = 100

[[menu.main]]
  name = "Seminar"
  url = "/categories/seminar/"
  weight = 99

[[menu.main]]
  name = "Photos"
  url = "/categories/photo/"
  weight = 98

[[menu.main]]
  name = "SNU Ling"
  url = "http://hosting01.snu.ac.kr/~linguist/"
  weight = 95